import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNavBar from "@/components/Header";
import Header from "@/components/Header";
import { getPayload } from "payload";
import config from '@/payload.config'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 1. Initialize Payload
  const payload = await getPayload({ config });

  // 2. Fetch the Header Global data
  const headerData = await payload.findGlobal({
    slug: 'header',
  });
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <Header data={headerData} />
        {children}
      </body>
    </html>
  );
}
